config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  get  'side_contents_get',  to: 'side_contents#show'
  get  'side_contents_edit', to: 'side_contents#edit'
  post 'side_contents_save', to: 'side_contents#save'
end

app/models/side_content.rb
class SideContent < ActiveRecord::Base
  unloadable

  def self.find_text(project_id)
    fav = SideContent.where(user_id: User.current.id, project_id: project_id).first
    fav ? fav.text : ""
  end

  def self.save_text(params)
    SideContent.transaction do
      common = SideContent.where(user_id: User.current.id, project_id: 0).first
      common ||= SideContent.new(user_id: User.current.id, project_id: 0)
      common.text = params[:common_text]
      common.save

      project = SideContent.where(user_id: User.current.id, project_id: params[:project_id]).first
      project ||= SideContent.new(user_id: User.current.id, project_id: params[:project_id])
      project.text = params[:project_text]
      project.save
    end
  end
end

app/controllers/side_contents_controller.rb
class SideContentsController < ApplicationController
  unloadable

  def show
    render_view
  end

  def edit
    render_view
  end

  def save
    SideContent.save_text(params)
    render_view
  end

  private
  def render_view
    @project      = Project.find(params[:project_id])
    @common_text  = SideContent.find_text(0)
    @project_text = SideContent.find_text(params[:project_id])

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/side_contents_helper.rb
module SideContentsHelper
end

app/views/side_contents/_form.html.erb
<%= form_tag side_contents_save_path, remote: true  do |f| %>

  <%= hidden_field_tag(:project_id, @project.id) %>

  <div>
    <h2><%= l(:side_contents_label_common) %></h2>
    <%= text_area_tag(:common_text, @common_text, style: 'width:100%;height:200px') %>
  </div>

  <div style='margin-top:10px;'>
    <h2><%= l(:side_contents_label_project) %></h2>
    <%= text_area_tag(:project_text, @project_text, style: 'width:100%;height:200px') %>
  </div>

  <div style="margin-top:10px;margin-right:-10px;" align="right">
    <%= submit_tag l(:side_contents_label_submit) %>
    <%= submit_tag l(:side_contents_label_cancel, :name => nil, :onclick => "hideModal(this);", :type => 'button') %>
  </div>

<% end %> 

app/views/side_contents/_side_contents.html.erb
<div id="side_contents">
  <div>
    <div style="float:right;color:#888;margin-right:10px;">
      <%
        url = ""
        url << config.relative_url_root if config.relative_url_root
        url << "/side_contents_edit?project_id=#{@project.id}"
      %>
      <%= link_to(l(:side_contents_label_edit), url, :remote => true, :method => 'get') %>
    </div>
    <h3>SideContents</h3>
    <div>
      <%= textilizable(@common_text,  object: @project) %>
      <%= textilizable(@project_text, object: @project) %>
    </div>
  </div>
</div>

app/views/side_contents/edit.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'form') %>');
showModal('ajax-modal', '600px');

app/views/side_contents/save.js.erb
$('#side_contents').html('<%= escape_javascript(render :partial => 'side_contents') %>');
hideModal();

app/views/side_contents/show.js.erb
<%= render :partial => 'side_contents' %>